ANNOTATION_ENABLED = "app.mintel.com/k8s-notify.enabled"
ANNOTATION_TEAM = "app.mintel.com/k8s-notify.team"
ANNOTATION_RECEIVER = "app.mintel.com/k8s-notify.receiver"
ANNOTATION_PUBLIC_URL = "app.mintel.com/k8s-notify.public-url"
ANNOTATION_MONITORING_URL = "app.mintel.com/k8s-notify.monitoring-url"
ANNOTATION_HEALTH_STATUS_URL = "app.mintel.com/k8s-notify.health-status-url"
ANNOTATION_VCS_URL = "app.mintel.com/k8s-notify.vcs-url"
