apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.mintel.com/k8s-notify.enabled: "true"
    app.mintel.com/k8s-notify.team: "myteam"
    app.mintel.com/k8s-notify.receiver: "flowdock"
    app.mintel.com/k8s-notify.public-url: "https://google.com/?q=pubic"
    app.mintel.com/k8s-notify.vcs-url: "https://google.com/?q=vcs"
    app.mintel.com/k8s-notify.health-status-url: "https://google.com/?q=healthz"
    app.mintel.com/k8s-notify.logs-url: "https://google.com/?q=logs"
    app.mintel.com/k8s-notify.monitoring-url: "https://google.com/?q=monitoring"
  labels:
    run: nginx
  name: nginx
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
