---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: k8s-notify
  name: k8s-notify
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-notify
  labels:
    k8s-app: k8s-notify
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-notify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-notify
subjects:
  - kind: ServiceAccount
    name: k8s-notify
    namespace: default
